os: linux
sudo: required
language: c

addons:
  apt:
    packages:
    - gcc
    - git 
    - cmake
    - zlib1g-dev
    - libzip-dev
    - apt-src
    - scons
    - p7zip-full
    - gawk
    - gzip
    - perl
    - autoconf
    - m4
    - automake
    - libtool
    - libncurses5-dev
    - gettext
    - gperf
    - dejagnu
    - expect
    - tcl
    - autogen
    - flex
    - flip
    - bison
    - tofrodos
    - texinfo
    - g++
    - gcc-multilib
    - libgmp3-dev
    - libmpfr-dev
    - debhelper
    - texlive
    - texlive-extra-utils
    - zip
    - binutils-mingw-w64-i686
    - binutils-mingw-w64-x86-64
    - gcc-mingw-w64
    - gcc-mingw-w64-i686
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64
    - g++-mingw-w64-i686
    - g++-mingw-w64-x86-64
    - patch
    
before_script:
    - mkdir /opt/vita
    - mkdir /opt/vita/toolchain
    - cd /opt/vita/toolchain
    - wget http://www.digip.org/jansson/releases/jansson-2.7.tar.gz
    - wget http://nih.at/libzip/libzip-1.1.3.tar.gz
    
script:
  - cd
  - ls build
