os: linux
sudo: required
language: c

addons:
  apt:
    packages:
    - gcc
    - git 
    - cmake
    - zlib1g-dev
    - libzip-dev
    - apt-src
    - scons
    - p7zip-full
    - gawk
    - gzip
    - perl
    - autoconf
    - m4
    - automake
    - libtool
    - libncurses5-dev
    - gettext
    - gperf
    - dejagnu
    - expect
    - tcl
    - autogen
    - flex
    - flip
    - bison
    - tofrodos
    - texinfo
    - g++
    - gcc-multilib
    - libgmp3-dev
    - libmpfr-dev
    - debhelper
    - texlive
    - texlive-extra-utils
    - zip
    - binutils-mingw-w64-i686
    - binutils-mingw-w64-x86-64
    - gcc-mingw-w64
    - gcc-mingw-w64-i686
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64
    - g++-mingw-w64-i686
    - g++-mingw-w64-x86-64
    - patch
    
before_script:
    - mkdir /opt/vita
    - mkdir /opt/vita/toolchain
    - cd /opt/vita/toolchain
    - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-src.tar.bz2
    - wget http://www.digip.org/jansson/releases/jansson-2.7.tar.gz
    - wget http://nih.at/libzip/libzip-1.1.3.tar.gz
    
script:
    - cd $TRAVIS_BUILD_DIR
    - cd ..
    - ls
    - tar xf /opt/vita/toolchain/gcc-arm-none-eabi-4_9-2015q2-20150609-src.tar.bz2
    - mv gcc-arm-none-eabi-4_9-2015q2-20150609 toolchain
    - cp -r buildscripts/* toolchain
    - cd toolchain/src
    - cp /opt/vita/toolchain/jansson-2.7.tar.gz .
    - cp /opt/vita/toolchain/libzip-1.1.3.tar.gz .
    - find -name '*.tar.*' | xargs -I% tar -xf %
    - rm -rf newlib
    - cd ..
    - patch -p1 < vita.patch
    - git clone https://github.com/vitasdk/vita-toolchain.git src/vita-toolchain
    - git clone https://github.com/vitasdk/vita-headers.git src/vita-headers
    - git clone https://github.com/vitasdk/newlib.git src/newlib
    - git clone https://github.com/vitasdk/pthread-embedded.git src/pthread-embedded
    - /bin/bash build-prerequisites.sh --skip_steps=mingw32
    - /bin/bash build-toolchain.sh --skip_steps=manual,mingw32
